version: '3'
services:
  influxdb:
    container_name: influxdb
    image: influxdb:1.7.9
    environment:
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
      - INFLUXDB_USER=telegraf
      - INFLUXDB_USER_PASSWORD=telegraf
    volumes:
      - /opt/data/influxdb/data:/var/lib/influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
  chronograf:
    container_name: chronograf
    image: chronograf:1.7
    command: --influxdb-url=http://influxdb:8086
    volumes:
      - /opt/data/chronograf/data:/var/lib/chronograf
    ports:
      - "8888:8888"
    links:
      - influxdb
  kapacitor:
    container_name: kapacitor
    image: kapacitor:1.5
    ports:
      - "9092:9092"
    environment:
      - KAPACITOR_INFLUXDB_0_URLS_0=http://influxdb:8086
    volumes:
      - /opt/data/kapacitor/data:/var/lib/kapacitor
    links:
      - influxdb
  grafana:
  #uid: 472 gid: 472
    container_name: grafana
    image: grafana/grafana:6.5.2
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-piechart-panel,flant-statusmap-panel,vonage-status-panel
    volumes:
      - /opt/data/grafana/data:/var/lib/grafana
    ports:
      - "3000:3000"
    links:
      - influxdb
